# Generated by Django 2.2.17 on 2021-06-12 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentcounter',
            options={'ordering': ('-period',), 'verbose_name': 'Индивид. счетчик (текущий)', 'verbose_name_plural': 'Индивид. счетчики (текущие)'},
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 265765), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 266542), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 261681), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 262465), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 273418), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 270904), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 267232), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 263235), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 21, 46, 14, 270190), verbose_name='Создан'),
        ),
    ]
