# Generated by Django 2.2.17 on 2021-04-23 21:02

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appartament",
            name="house",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.House", verbose_name="Дом"
            ),
        ),
        migrations.AlterField(
            model_name="appartament",
            name="number",
            field=models.PositiveIntegerField(verbose_name="Номер квартиры"),
        ),
        migrations.AlterField(
            model_name="appartament",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Жилец",
            ),
        ),
        migrations.AlterField(
            model_name="historycounter",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="category_rate",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.ServicesCategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.City", verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="street",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.Street", verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="uk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mainapp.UK",
                verbose_name="Управляющая компания",
            ),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="house",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.House", verbose_name="Дом"
            ),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 21, 2, 35, 829608), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="house",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.House", verbose_name="Дом"
            ),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 21, 2, 35, 830381), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="privileges",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service",
                to="mainapp.Services",
                verbose_name="Услуга",
            ),
        ),
        migrations.AlterField(
            model_name="profit",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="recalculations",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="mainapp.ServicesCategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit",
                to="mainapp.Metrics",
                verbose_name="Единицы",
            ),
        ),
        migrations.AlterField(
            model_name="standart",
            name="house",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.House", verbose_name="Дом"
            ),
        ),
        migrations.AlterField(
            model_name="uk",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.City", verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="uk",
            name="street",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mainapp.Street", verbose_name="Улица"
            ),
        ),
        migrations.CreateModel(
            name="PersonalAccountStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7, verbose_name="Сумма")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние счета",
                "verbose_name_plural": "Состояния счетов",
                "ordering": ("-updated",),
            },
        ),
    ]
