# Generated by Django 2.2.17 on 2021-04-20 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 12, 24, 48, 617685), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 12, 24, 48, 618302), verbose_name='Создан'),
        ),
        migrations.AlterUniqueTogether(
            name='housecurrent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='househistory',
            unique_together=set(),
        ),
    ]
