# Generated by Django 2.2.24 on 2021-06-16 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 201697), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 202390), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 197571), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 198248), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 210031), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 208753), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 203347), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 199090), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 49, 20, 206363), verbose_name='Создан'),
        ),
    ]
