# Generated by Django 2.2.17 on 2021-04-26 02:25

import datetime

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0002_auto_20210423_2102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appartament",
            name="num_owner",
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Кол-во проживающих"),
        ),
        migrations.AlterField(
            model_name="appartament",
            name="sq_appart",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="0", max_digits=5, null=True, verbose_name="Площадь"
            ),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 2, 25, 43, 987864), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 2, 25, 43, 988784), verbose_name="Создан"),
        ),
        migrations.AlterUniqueTogether(
            name="appartament",
            unique_together={("house", "number", "add_number", "user")},
        ),
    ]
