# Generated by Django 2.2.17 on 2021-04-22 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210422_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 17, 4, 38, 346316), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 17, 4, 38, 347272), verbose_name='Создан'),
        ),
    ]
