# Generated by Django 2.2.24 on 2021-06-25 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210616_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активная')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('-updated',), 'verbose_name': 'Дом', 'verbose_name_plural': '007 Дома'},
        ),
        migrations.AlterModelOptions(
            name='housecurrent',
            options={'ordering': ('-updated',), 'verbose_name': 'Домовой счетчик (текущий)', 'verbose_name_plural': 'Домовые счетчики (текущие)'},
        ),
        migrations.AlterModelOptions(
            name='recalculations',
            options={'ordering': ('-updated',), 'verbose_name': 'Перерасчет', 'verbose_name_plural': 'Перерасчеты'},
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 978536), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 979193), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 974633), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 975453), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 986226), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 985129), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 980013), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 976315), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 45, 44, 983974), verbose_name='Создан'),
        ),
    ]
