# Generated by Django 2.2.17 on 2021-06-13 11:40

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20210612_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablepayments',
            options={'ordering': ('-period',), 'verbose_name': 'Платеж (перепенные)', 'verbose_name_plural': 'Платежи (переменные)'},
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 387690), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 388602), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 383092), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 383982), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 396837), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 395343), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 389386), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 384824), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 40, 21, 392795), verbose_name='Создан'),
        ),
        migrations.CreateModel(
            name='HeaderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Данные')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
            },
        ),
    ]
