# Generated by Django 2.2.24 on 2021-06-29 03:40

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210629_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='header_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1, verbose_name='Данные для шапки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 922236), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 923106), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 917364), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 918384), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 931485), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 929444), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 924007), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 919253), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 3, 38, 21, 928190), verbose_name='Создан'),
        ),
    ]
