# Generated by Django 2.2.17 on 2021-04-29 02:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_auto_20210429_0253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appartament",
            name="number",
            field=models.CharField(max_length=3, verbose_name="Номер квартиры"),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 2, 58, 49, 510306), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 2, 58, 49, 511083), verbose_name="Создан"),
        ),
    ]
