# Generated by Django 2.2.24 on 2021-06-30 02:24

import datetime

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_auto_20210629_0340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentcounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 567990), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="historycounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 568711), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 563296), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 564172), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="mainbook",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 575937), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="header_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True, verbose_name="Данные для шапки"
            ),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 576888), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="recalculations",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 569651), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="standart",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 565126), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="variablepayments",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 2, 24, 29, 573912), verbose_name="Создан"),
        ),
    ]
