# Generated by Django 2.2.17 on 2021-04-30 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210430_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='add_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 13, 32, 49, 817718), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 13, 32, 49, 818381), verbose_name='Создан'),
        ),
    ]
