# Generated by Django 2.2.24 on 2021-08-21 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210821_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='averageсalculationbuffer',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 726692), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 720907), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 721501), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 718795), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 719426), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 724605), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 725285), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 722239), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 720157), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 50, 18, 723598), verbose_name='Период'),
        ),
    ]
