# Generated by Django 2.2.17 on 2021-06-05 10:58

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_auto_20210430_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appartament",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appartament",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Жилец",
            ),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 58, 19, 539696), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 10, 58, 19, 540512), verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "М"), ("W", "Ж")], default=None, max_length=1, null=True, verbose_name="Пол"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="type_electric_meter",
            field=models.CharField(
                blank=True,
                choices=[("1", "однотарифный"), ("2", "двухтарифный"), ("3", "многотарифный")],
                default=None,
                max_length=1,
                null=True,
                verbose_name="Тип счетчика",
            ),
        ),
    ]
