# Generated by Django 2.2.24 on 2021-08-14 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210703_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageсalculationbuffer',
            name='col_water',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True, verbose_name='Буффер холодной воды'),
        ),
        migrations.AlterField(
            model_name='averageсalculationbuffer',
            name='hot_water',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, null=True, verbose_name='Буффер горячей воды'),
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 656065), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 659086), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 651768), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 652379), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 664566), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 665449), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 660187), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 653330), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 11, 9, 12, 662949), verbose_name='Создан'),
        ),
    ]
