# Generated by Django 2.2.24 on 2021-08-21 20:07

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0011_auto_20210821_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averageсalculationbuffer",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 962705), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="averageсalculationbuffer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
        migrations.AlterField(
            model_name="currentcounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 956922), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="historycounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 957500), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 955114), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 955632), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="mainbook",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 960550), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 961246), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="recalculations",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 958147), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="standart",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 956301), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="variablepayments",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 20, 7, 9, 959508), verbose_name="Период"),
        ),
        migrations.AlterUniqueTogether(
            name="averageсalculationbuffer",
            unique_together={("user", "period")},
        ),
    ]
