# Generated by Django 2.2.24 on 2021-08-15 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210815_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageсalculationbuffer',
            name='col_water',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Буффер холодной воды'),
        ),
        migrations.AlterField(
            model_name='averageсalculationbuffer',
            name='hot_water',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Буффер горячей воды'),
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 714363), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 716126), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 710738), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 711329), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 720843), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 721493), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 716871), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 712027), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 19, 7, 3, 719396), verbose_name='Создан'),
        ),
    ]
