# Generated by Django 2.2.24 on 2021-08-22 21:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_auto_20210821_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averageсalculationbuffer",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 800298), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="currentcounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 794400), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="historycounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 795279), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 792382), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 792968), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="mainbook",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 798202), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 798953), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="recalculations",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 795928), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="standart",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 793694), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="variablepayments",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 21, 14, 0, 797089), verbose_name="Период"),
        ),
    ]
