# Generated by Django 2.2.24 on 2021-08-24 23:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_merge_20210823_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averageсalculationbuffer",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 619559), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="currentcounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 613949), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="historycounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 614455), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 612031), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 612611), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="mainbook",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 617430), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 618103), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="recalculations",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 615030), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="standart",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 613223), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="variablepayments",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 23, 21, 2, 616346), verbose_name="Период"),
        ),
    ]
