# Generated by Django 2.2.24 on 2021-09-07 19:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_auto_20210824_2321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="averageсalculationbuffer",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 113132), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="currentcounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 108017), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="historycounter",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 108500), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="housecurrent",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 106366), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="househistory",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 106881), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="mainbook",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 111132), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 111883), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="recalculations",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 109138), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="standart",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 107429), verbose_name="Период"),
        ),
        migrations.AlterField(
            model_name="variablepayments",
            name="period",
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 19, 24, 16, 110199), verbose_name="Период"),
        ),
    ]
