# Generated by Django 2.2.24 on 2021-08-17 12:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20210816_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 954394), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 955969), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='col_water',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Хол.вода'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='hot_water',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Гор.вода'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 949546), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 950240), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 961322), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 963019), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 957425), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 951116), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 12, 48, 10, 959769), verbose_name='Создан'),
        ),
    ]
