# Generated by Django 2.2.24 on 2021-08-17 13:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210817_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 350910), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 351816), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 345972), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='col_water',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Хол.вода'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='hot_water',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Гор.вода'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 346867), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 356780), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 357463), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 352891), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 347871), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 13, 5, 29, 355331), verbose_name='Создан'),
        ),
    ]
