# Generated by Django 2.2.24 on 2021-08-17 14:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210817_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uk',
            name='city',
        ),
        migrations.RemoveField(
            model_name='uk',
            name='street',
        ),
        migrations.RemoveField(
            model_name='house',
            name='uk',
        ),
        migrations.RemoveField(
            model_name='housecurrent',
            name='electric_day',
        ),
        migrations.RemoveField(
            model_name='housecurrent',
            name='electric_night',
        ),
        migrations.RemoveField(
            model_name='househistory',
            name='electric_day',
        ),
        migrations.RemoveField(
            model_name='househistory',
            name='electric_night',
        ),
        migrations.RemoveField(
            model_name='standart',
            name='electric_day',
        ),
        migrations.RemoveField(
            model_name='standart',
            name='electric_night',
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 799281), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 799759), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 796382), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 796942), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 804502), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 805222), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 800347), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='services',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='col_water',
            field=models.DecimalField(decimal_places=6, max_digits=11, verbose_name='Норматив ХВС'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='hot_water',
            field=models.DecimalField(decimal_places=6, max_digits=11, verbose_name='Норматив ХГС'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 797475), verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 6, 37, 803224), verbose_name='Создан'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UK',
        ),
    ]
