# Generated by Django 2.2.24 on 2021-09-07 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20210824_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='add_number',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='appartament',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер квартиры'),
        ),
    ]
