# Generated by Django 2.2.17 on 2021-04-10 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 21, 6, 34, 695601, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
