# Generated by Django 2.2.24 on 2021-06-16 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 2, 49, 20, 189889, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
