# Generated by Django 2.2.17 on 2021-04-13 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 7, 26, 19, 738671, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
