# Generated by Django 2.2.17 on 2021-06-13 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20210612_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 11, 40, 21, 373871, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
