# Generated by Django 2.2.17 on 2021-04-21 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20210420_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 3, 55, 24, 622804, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
