# Generated by Django 2.2.17 on 2021-04-22 17:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20210422_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 17, 4, 38, 337158, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
