# Generated by Django 2.2.17 on 2021-04-29 02:51

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0003_auto_20210426_0225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 5, 1, 2, 51, 18, 813282, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
