# Generated by Django 2.2.17 on 2021-06-14 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_auto_20210613_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 7, 8, 6, 386140, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
