# Generated by Django 2.2.24 on 2021-06-29 03:19

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0004_auto_20210625_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 7, 1, 3, 19, 56, 368161, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
