# Generated by Django 2.2.24 on 2021-08-20 19:53

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0004_auto_20210820_1953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 8, 22, 19, 53, 27, 99345, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
