# Generated by Django 2.2.24 on 2021-06-29 03:40

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0005_auto_20210629_0319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 7, 1, 3, 38, 21, 908548, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
