# Generated by Django 2.2.17 on 2021-04-29 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_auto_20210429_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 2, 58, 49, 502624, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
