# Generated by Django 2.2.17 on 2021-04-30 13:31

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_auto_20210429_0258"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 5, 2, 13, 31, 10, 235345, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
