# Generated by Django 2.2.24 on 2021-06-30 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20210629_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 2, 24, 29, 555041, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
