# Generated by Django 2.2.17 on 2021-04-30 13:32

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20210430_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 5, 2, 13, 32, 49, 811053, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
