# Generated by Django 2.2.24 on 2021-07-01 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_auto_20210630_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 6, 31, 56, 265053, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
