# Generated by Django 2.2.24 on 2021-07-03 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_auto_20210701_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 6, 52, 20, 590637, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
