# Generated by Django 2.2.17 on 2021-06-05 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20210430_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 10, 58, 19, 531690, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
