# Generated by Django 2.2.24 on 2021-07-03 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20210703_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 36, 20, 471531, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
