# Generated by Django 2.2.24 on 2021-08-14 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0010_auto_20210703_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 11, 9, 12, 644296, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
