# Generated by Django 2.2.24 on 2021-08-21 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0011_auto_20210821_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 20, 7, 9, 944622, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
