# Generated by Django 2.2.24 on 2021-08-15 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0013_auto_20210815_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 19, 7, 3, 703739, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
