# Generated by Django 2.2.24 on 2021-08-15 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0014_auto_20210815_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 19, 46, 45, 916611, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
