# Generated by Django 2.2.24 on 2021-08-15 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0015_auto_20210815_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 20, 4, 55, 531730, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
