# Generated by Django 2.2.24 on 2021-08-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0015_auto_20210823_2106'),
        ('authnapp', '0015_auto_20210822_2140'),
    ]

    operations = [
    ]
