# Generated by Django 2.2.24 on 2021-08-15 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0017_auto_20210815_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 21, 15, 11, 961184, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
