# Generated by Django 2.2.24 on 2021-08-16 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0019_auto_20210815_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 20, 22, 0, 132318, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
