# Generated by Django 2.2.24 on 2021-08-16 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0020_auto_20210816_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 21, 20, 19, 612955, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
