# Generated by Django 2.2.24 on 2021-08-17 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0025_auto_20210817_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 19, 0, 36, 394053, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Если это житель поставьте галку.', verbose_name='Пользователь'),
        ),
    ]
