# Generated by Django 2.2.24 on 2022-01-27 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageсalculationbuffer',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 416019), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 411913), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 412365), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 410353), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 410865), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 414473), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 415056), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 412803), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 411445), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 1, 1, 11, 41, 38, 413652), verbose_name='Период'),
        ),
    ]
