# Generated by Django 2.2.24 on 2021-10-09 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210907_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageсalculationbuffer',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 929963), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='currentcounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 925268), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='historycounter',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 925651), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='housecurrent',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 924001), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='househistory',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 924376), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='mainbook',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 928370), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 928913), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='recalculations',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 926743), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='standart',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 924801), verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='variablepayments',
            name='period',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 39, 927587), verbose_name='Период'),
        ),
    ]
