# Generated by Django 2.2.24 on 2021-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalacc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='key_ya',
            field=models.CharField(blank=True, help_text='1888f9f3-1174-48c4-b1b4-fa129bй2345234', max_length=128, verbose_name='Api-ключ Яндекса'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lat',
            field=models.CharField(blank=True, help_text='57.167979', max_length=64, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lon',
            field=models.CharField(blank=True, help_text='65.564430', max_length=64, verbose_name='Долгота'),
        ),
    ]
