# Generated by Django 2.2.24 on 2022-01-27 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 11, 41, 38, 401723, tzinfo=utc), verbose_name='Актуальность ключа'),
        ),
    ]
