# Generated by Django 2.2.24 on 2021-09-07 19:25

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0018_auto_20210907_1924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 9, 9, 19, 25, 6, 729875, tzinfo=utc), verbose_name="Актуальность ключа"
            ),
        ),
    ]
