# Generated by Django 2.2.24 on 2021-08-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type_electric_meter',
        ),
    ]
