# Generated by Django 2.2.24 on 2021-08-23 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_auto_20210823_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="number",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Номер",
            ),
        ),
    ]
