# Generated by Django 2.2.24 on 2021-08-24 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20210823_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер'),
        ),
    ]
